name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-test:
    name: Build, test, and format
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race ./...

    - name: Format
      if: matrix.platform == 'ubuntu-latest'
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

  storage-integration-test:
    name: >
      Storage integration tests.
      Currently only supports the MySQL backend.
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
        include:
          - storage: "mysql"
            mysql-version: ['8.0']
            args: "-dsn 'nanomdm:nanomdm@tcp(localhost)/nanomdm'"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql-version }}
          mysql database: 'nanomdm'
          mysql user: 'nanomdm'
          mysql password: 'nanomdm'
        if: ${{ matrix.storage }} == 'mysql'

    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: go test -v --tags=integration ./storage/${{ matrix.storage }}/ -args ${{ matrix.args }}
